Virtual_teacher/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index,name='index'),
    path('account/', include('account.urls')),
    path('learn/', include('learn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("register/", register, name="register"),#url на страницу регистрации
    path("login/", user_login, name="login"),#url на страницу входа
    path("logout/", LogoutView.as_view(next_page="index"), name="logout"),#выход из аккаунта
    path("profile/", profile, name="profile"),#url на страницу профиля
    path("edit-profile/", edit_profile, name="edit"),#url на станицу редактирования профиля
]

learn/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static#для работы с медиа из статических файлов

urlpatterns = [
    path('study/',views.study,name="study"),#страница с вариантами обучения
    path('study/ai-teacher/', views.ai_teacher, name='ai-teacher'),#ИИ учитель
    path('chat/',views.chat_with_gemini, name='chat_with_gemini'),#чат 
    path('chat/history/', views.get_chat_history, name='get_chat_history'),#загрузка истории чата 
    path('all-courses/', views.all_courses, name='all_courses'),#все курсы
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),#страница курса
    path('about-us', views.about_us, name='about-us'),#о нас
    path('news/', views.news, name='news'),#новости
    path('mood-text/', views.mood_text, name='mood-text'),#нейросеть(определение настоения текста)
    path("mood-text/chat/", views.mood_text_chat, name="mood_text_chat"),#чат с нейросетью
    path('test/<int:course_id>/',views.test_in_course,name='test'),#тест
    path('search/',views.search_user,name='search-user'),#поиск пользователей
    path('message/', views.messages_view, name='message'),  # Для страницы всех сообщений
    path('message/<int:chat_id>/', views.messages_view, name='message_with_id'),# Страница со всеми чатами
    path('start_chat/<int:user_id>/', views.start_chat, name='start_chat'),#начать чат с пользователм
    path('message/send/<int:chat_id>/', views.send_message, name='send_message'),#отправить сообщение
    path('courses/category/<int:category_id>/', views.category_courses, name='category_courses'),#курсы по категориям
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#поключение медиа статических файлов

account/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)#почта
    age = models.PositiveIntegerField(null=True, blank=True)#возраст(не обязательно)
    courses_completed = models.PositiveIntegerField(default=0)#кол-во выполненных курсов(по умолчанию 0)
    date_joined = models.DateTimeField(auto_now_add=True)#дата регистрации
    score = models.PositiveIntegerField(default=0)#очки(по умолчанию 0)
    role = models.CharField(max_length=20, default='Участник')#роль(зависит от очков и по умолчанию "Участник")

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_role(self):
        #Роль зависит от очков. Это создано для мотивации :)
        if self.is_superuser:#Если админ, то роль админ
            return "Админ"
        elif self.score >= 1000:#Если больше или равно 1000 очков, то роль робот
            return "Робот"
        elif self.score > 200:#Если больше 200 очков, то роль сверхразум
            return "Сверхразум"
        elif self.score > 100:#если больше 100 очков, то роль отличник
            return "Отличник"
        elif self.score > 10:#если больше 10 очков, то роль хорошист
            return "Хорошист"
        return "Участник"

    def save(self, *args, **kwargs):
        #Автоматически обновляет роль перед сохранением
        self.role = self.get_role()
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.username} ({self.get_role()})"

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()#Вызываем нашу модель чтобы писать не CustomUser, а просто User

class LoginForm(forms.Form):#Форма для входа
    username = forms.CharField(label="Имя пользователя", widget=forms.TextInput(attrs={"class": "form-control-login", "placeholder": "Введите имя"}))
    password = forms.CharField(label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-control-login", "placeholder": "Введите email"}))


class ProfileUpdateForm(forms.ModelForm):#Форма для реадктирования профиля
    username = forms.CharField(
        label="Имя пользователя",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Введите имя"})
    )
    email = forms.EmailField(
        label="Электронная почта",
        widget=forms.EmailInput(attrs={"class": "form-control", "placeholder": "Введите email"})
    )
    age = forms.IntegerField(
        label="Возраст",
        required=False,
        widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "Введите возраст"})
    )

    class Meta:
        model = User
        fields = ["username", "email", "age"]



class CustomUserCreationForm(UserCreationForm):#Форма для регистрации
    username = forms.CharField(
        label="Имя пользователя",
        widget=forms.TextInput(attrs={"class": "form-control-login", "placeholder": "Введите имя"}),
        error_messages={"unique": "Этот логин уже занят"}#Если занять логин, то отпраыляет ошибку
    )
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(attrs={"class": "form-control-login", "placeholder": "Введите email"}),
        error_messages={"invalid": "Введите корректный email"}#Если email не соответсвует(не рабочий) тоже отправляет ошибку
    )
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control-login", "placeholder": "Введите пароль"}),
        error_messages={#проверка на длинну и сложность пароля
            "password_too_short": "Пароль должен содержать минимум 8 символов",
            "password_too_common": "Пароль слишком простой",
            "password_entirely_numeric": "Пароль не должен состоять только из цифр"
        }
    )
    password2 = forms.CharField(
        label="Повторите пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control-login", "placeholder": "Повторите пароль"}),
        error_messages={"password_mismatch": "Пароли не совпадают"}#Если пароли не совподают
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

account/views.py
from django.contrib.auth import get_user_model, login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomUserCreationForm
from .forms import ProfileUpdateForm 
User = get_user_model()#Наша модель, чтобы писать User , а не CustomUser

def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():#Если форма валидна(проверяется в forms.py), то идет запись пользовтаеля в БД
            user = form.save()#Сохранение в БД
            #print(user) это был отладочный принт
            login(request, user)  
            messages.success(request, "Регистрация успешна!")
            return redirect("profile") #После регистрации отправляет на страницу профиля
        else:
            messages.error(request, "Ошибка при регистрации. Проверьте данные.") #если форма не валидна
    else:
        form = CustomUserCreationForm()
    return render(request, "register.html", {"form": form})

def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():#если форма валидна(корректна)
            user = form.get_user()
            login(request, user)#вход в систему
            messages.success(request, "Вы вошли в систему!")
            return redirect("profile") 
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})

@login_required(login_url="login")#можно зайти только если выполнен вход в систему, а иначе перекидывает на страницу входа
def profile(request):
    return render(request, "profile.html", {"user": request.user})


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():#Проверяет форму на корректность 
            form.save()#сохраняет  изменения в БД
            messages.success(request, "Профиль успешно обновлён!")
            return redirect("profile") 
    else:
        form = ProfileUpdateForm(instance=request.user)

    return render(request, "edit_profile.html", {"form": form})

account/templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Редактирование профиля</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
    <header><!--Шапка-->
        <a href="{% url 'index' %}" class="header-h1">Виртуальный учитель</a>
        <div class="var">
            <div class="dropdown">
                <a href="{% url 'profile'%}" class="main-link">Аккаунт</a>
                <div class="dropdown-content">
                    <a href="{% url 'register'%}">Зарегистрироваться</a>
                    <a href="{% url 'login'%}">Войти</a>
                    <a href="{% url 'search-user'%}">Найти пользователя</a>
                    <a href="{% url 'message'%}">Сообщения</a>
                </div>
            </div>
            <div class="dropdown">
                <a href="{% url 'study' %}" class="main-link">Обучение</a>
                <div class="dropdown-content">
                    <a href="{% url 'ai-teacher' %}">Учитель</a>
                    <a href="{% url 'all_courses' %}">Курсы(темы)</a>
                </div>
            </div>
    
            <div class="dropdown">
                <a href="{% url 'news' %}" class="main-link">Новости</a>
                <div class="dropdown-content">
                    <div class="sub-dropdown">
                        <a href="{% url 'mood-text' %}" class="main-link">Новые функции</a>
                    </div>
                </div>
            </div>
            <a href="{% url 'about-us' %}" class="main-link">О нас</a>
        </div>
    </header>
    <div style="display: block; justify-content: center; align-items: center; margin-top: 50px; width: 80%; min-width: 600px; max-width: 90%; margin-left: auto; margin-right: auto;">
        <div class="dark-box" style="min-width: 1000px; text-align: center;">
            <h1>Редактировать профиль</h1><br>
            <form method="post" style="display: block;">
                {% csrf_token %}<!--Поля редактирования(Имя пользователя, почта, возраст)-->
                <label for="id_username">Имя пользователя:</label>
                {{ form.username }}
                <br><br>
                <label for="id_email">Электронная почта:</label>
                {{ form.email }}
                <br><br>
                <label for="id_age">Возраст:</label>
                {{ form.age }}
                <br><br>
                <button type="submit" style="background-color: #F4E1FF;border-radius: 30px;font-size: 35px;color: #3F005F;padding: 5px;
                font-weight: 600;border: None;cursor: pointer;">Сохранить изменения</button><!--Отпрвка изменений-->
            </form>
            
        </div>
    </div>
</body>
</html>

account/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Вход</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
    <header><!--Шапка-->
        <a href="{% url 'index' %}" class="header-h1">Виртуальный учитель</a>
        <div class="var">
            <div class="dropdown">
                <a href="{% url 'profile'%}" class="main-link">Аккаунт</a>
                <div class="dropdown-content">
                    <a href="{% url 'register'%}">Зарегистрироваться</a>
                    <a href="{% url 'login'%}">Войти</a>
                    <a href="{% url 'search-user'%}">Найти пользователя</a>
                    <a href="{% url 'message'%}">Сообщения</a>
                </div>
            </div>
            <div class="dropdown">
                <a href="{% url 'study' %}" class="main-link">Обучение</a>
                <div class="dropdown-content">
                    <a href="{% url 'ai-teacher' %}">Учитель</a>
                    <a href="{% url 'all_courses' %}">Курсы(темы)</a>
                </div>
            </div>
    
            <div class="dropdown">
                <a href="{% url 'news' %}" class="main-link">Новости</a>
                <div class="dropdown-content">
                    <div class="sub-dropdown">
                        <a href="{% url 'mood-text' %}" class="main-link">Новые функции</a>
                    </div>
                </div>
            </div>
            <a href="{% url 'about-us' %}" class="main-link">О нас</a>
        </div>
    </header>
    <div style="display: flex; justify-content: center; margin-top: 50px;">
        <div class="dark-box" style="min-width: 600px; text-align: center;">
            <h1>Вход</h1>
            <br>
            {% if form.errors %}<!--Если форма неверная(возращается из views.py , то выводиться ошибка)-->
                <p style="color: rgb(255, 225, 0);">Неверное имя пользователя или пароль</p>
            {% endif %}
            
            <form method="post"><!--Поля ввода данных для входа-->
                {% csrf_token %}
                
                <label for="username">Имя пользователя:</label><br>
                <input type="text" id="username" name="username" class="form-control-login" placeholder="Введите имя" required><br><br>
                
                <label for="password">Пароль:</label><br>
                <input type="password" id="password" name="password" class="form-control-login" placeholder="Введите пароль" required><br><br>
                
                <button type="submit" class="btn-login">Войти</button>
            </form>
            
            
            <br>
            <p>Нет аккаунта? <a href="{% url 'register' %}" style="color: rgb(255, 192, 33);">Зарегистрироваться</a></p><!--Если нет аккаунта , то зарегетаться-->
        </div>
    </div>
</body>
</html>

account/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Профиль {{ user.username }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
    <header>
        <a href="{% url 'index' %}" class="header-h1">Виртуальный учитель</a>
        <div class="var">
            <div class="dropdown">
                <a href="{% url 'profile'%}" class="main-link">Аккаунт</a>
                <div class="dropdown-content">
                    <a href="{% url 'register'%}">Зарегистрироваться</a>
                    <a href="{% url 'login'%}">Войти</a>
                    <a href="{% url 'search-user'%}">Найти пользователя</a>
                    <a href="{% url 'message'%}">Сообщения</a>
                </div>
            </div>
            <div class="dropdown">
                <a href="{% url 'study' %}" class="main-link">Обучение</a>
                <div class="dropdown-content">
                    <a href="{% url 'ai-teacher' %}">Учитель</a>
                    <a href="{% url 'all_courses' %}">Курсы(темы)</a>
                </div>
            </div>
    
            <div class="dropdown">
                <a href="{% url 'news' %}" class="main-link">Новости</a>
                <div class="dropdown-content">
                    <div class="sub-dropdown">
                        <a href="{% url 'mood-text' %}" class="main-link">Новые функции</a>
                    </div>
                </div>
            </div>
            <a href="{% url 'about-us' %}" class="main-link">О нас</a>
        </div>
    </header>

    <div style="display: flex; justify-content: center; align-items: center; margin-top: 50px; width: 80%; min-width: 600px; max-width: 90%; margin-left: auto; margin-right: auto;">
        <div class="dark-box" style="min-width: 1000px; text-align: center;">
            <h1>Профиль</h1><br>
            <div style="display: flex;"><!--Данные пользователя-->
                <h2 style="font-weight: 600;">Имя пользователя:</h2> <p style="font-size: 30px;font-weight: 800;color: #F4E1FF;">{{user.username}}</p>
            </div><br>
            <div style="display: flex;">
                <h2 style="font-weight: 600;">Ваша роль:</h2> <p style="font-size: 30px;font-weight: 800;color: #73ff00;">{{user.role}}</p>
            </div><br>
            <div style="display: flex;">
                <h2 style="font-weight: 600;">Курсов пройдено:</h2> <p style="font-size: 30px;font-weight: 800;color: #F4E1FF;">{{user.courses_completed}}</p>
            </div><br>
            <div style="display: flex;">
                <h2 style="font-weight: 600;">Очки:</h2> <p style="font-size: 30px;font-weight: 800;color: #F4E1FF;">{{user.score}}</p>
            </div><br>
            <div style="display: flex;">
                <h2 style="font-weight: 600;">Возраст:</h2> <p style="font-size: 30px;font-weight: 800;color: #F4E1FF;">{{user.age}}</p>
            </div><br>
            <div style="display: flex;">
                <h2 style="font-weight: 600;">Дата регистриции:</h2> <p style="font-size: 30px;font-weight: 800;color: #F4E1FF;">{{user.date_joined}}</p>
            </div><br><br>
            <div style="display: flex;">
                <a href="{% url 'edit' %}" style="margin-right: auto;margin-left: auto;"><!--Кнопка реадатирования-->
                    <button type="submit" style="background-color: #F4E1FF;border-radius: 30px;font-size: 35px;color: #3F005F;padding: 5px;font-weight: 600;border: None;    cursor: pointer;">Редактировать</button>
                </a>
                <form action="{% url 'logout' %}" method="post"  style="margin-right: auto;margin-left: auto;">
                    {% csrf_token %}<!--Кнопка выхода-->
                    <button type="submit" style="background-color: #F5E71C;border-radius: 30px;font-size: 35px;color: #6607e2;padding: 5px;width: 300px;;font-weight: 600;border: None;    cursor: pointer;">Выйти</button>
                </form>
            </div>                
    </div>
</body>
</html>

account/templates/register.html
{% load static %}<!--Загружаем статические файлы-->
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css">
</head>
<body>
    <header><!--Шапка-->
        <a href="{% url 'index' %}" class="header-h1">Виртуальный учитель</a>
        <div class="var">
            <div class="dropdown">
                <a href="{% url 'profile'%}" class="main-link">Аккаунт</a>
                <div class="dropdown-content">
                    <a href="{% url 'register'%}">Зарегистрироваться</a>
                    <a href="{% url 'login'%}">Войти</a>
                    <a href="{% url 'search-user'%}">Найти пользователя</a>
                    <a href="{% url 'message'%}">Сообщения</a>
                </div>
            </div>
            <div class="dropdown">
                <a href="{% url 'study' %}" class="main-link">Обучение</a>
                <div class="dropdown-content">
                    <a href="{% url 'ai-teacher' %}">Учитель</a>
                    <a href="{% url 'all_courses' %}">Курсы(темы)</a>
                </div>
            </div>
    
            <div class="dropdown">
                <a href="{% url 'news' %}" class="main-link">Новости</a>
                <div class="dropdown-content">
                    <div class="sub-dropdown">
                        <a href="{% url 'mood-text' %}" class="main-link">Новые функции</a>
                    </div>
                </div>
            </div>
            <a href="{% url 'about-us' %}" class="main-link">О нас</a>
        </div>
    </header>

    <div style="display: flex; justify-content: center; margin-top: 50px;">
        <div class="dark-box" style="min-width: 600px; text-align: center;">
            <h1>Регистрация</h1><br>
            <form method="post">
                {% csrf_token %}
                <!--Поля ввода даннных для регистрации-->
                <label for="username">Имя пользователя:</label><br>
                <input type="text" id="username" name="username" class="form-control-login" placeholder="Введите имя" required><br><br>
                
                <label for="email">Email:</label><br>
                <input type="email" id="email" name="email" class="form-control-login" placeholder="Введите email" required><br><br>
                
                <label for="password1">Пароль:</label><br>
                <input type="password" id="password1" name="password1" class="form-control-login" placeholder="Введите пароль" required><br><br>
                
                <label for="password2">Повторите пароль:</label><br>
                <input type="password" id="password2" name="password2" class="form-control-login" placeholder="Повторите пароль" required><br><br>
                {% if form.errors %}
                <div class="error-messages" style="color: rgb(255, 255, 0);font-size: 15px;">
                    <ul><!--Здесь выводятся ошибки
                        По типу: имя пользователя/почта уже заняты ли пароль слишком легкий и тд-->
                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}<br>
                <button type="submit" class="btn-reg">Зарегистрироваться</button><!--Кнопка для отправки данных на регистрацию-->
            </form><br>
            <p>Уже есть аккаунт? <a href="{% url 'login' %}"  style="color: rgb(255, 192, 33);">Войти</a></p><!--Если есть аккаунт,то войти-->
        </div>
    </div>
</body>
</html>